"""Tensor-level attention feasibility utilities (research only).

Not wired into ExactKV default generation or model inference.
"""

from exactkv.attention.streaming_quant_attention import (
    EXPERIMENT_066_ID,
    EXP066_CLAIM_NOTE,
    FORBIDDEN_ATTENTION_CLAIMS,
    AttentionFeasibilityResult,
    MemoryAccounting,
    QuantizedKV,
    attention_full,
    attention_materialized_compressed,
    attention_streaming_compressed,
    dequantize_kv_materialized,
    estimate_attention_memory_bytes,
    quantize_kv_int8_reference,
    run_attention_feasibility_cell,
    validate_exp066_report,
)

from exactkv.attention.hf_single_layer_probe import (
    DEFAULT_MODEL_ID,
    EXPERIMENT_067_ID,
    EXPERIMENT_068_ID,
    EXP067_CLAIM_NOTE,
    EXP068_CLAIM_NOTE,
    compute_drift_metrics,
    extract_qkv_from_qwen2_layer,
    extract_qwen_model_architecture,
    probe_qwen_architecture_support,
    run_exp067_probe,
    run_exp068_probe,
    run_hf_attention_drift_cell,
    validate_exp067_report,
    validate_exp068_report,
)

from exactkv.attention.hf_multilayer_probe import (
    EXPERIMENT_069_ID,
    EXPERIMENT_070_ID,
    EXP069_CLAIM_NOTE,
    EXP070_CLAIM_NOTE,
    PHASE16D_REGRESSION_CELL,
    run_exp069_probe,
    run_exp070_probe,
    validate_exp069_report,
    validate_exp070_report,
)

from exactkv.attention.hf_full_replay_probe import (
    EXPERIMENT_071_ID,
    EXPERIMENT_072_ID,
    EXPERIMENT_073_ID,
    EXP071_CLAIM_NOTE,
    EXP072_CLAIM_NOTE,
    EXP073_CLAIM_NOTE,
    run_exp071_probe,
    run_exp072_probe,
    run_exp073_probe,
    validate_exp071_report,
    validate_exp072_report,
    validate_exp073_report,
)

from exactkv.attention.tolerance_policy import (
    EXPERIMENT_074_ID,
    EXP074_CLAIM_NOTE,
    AttentionTolerancePolicy,
    AttentionToleranceDecision,
    OfflineAttentionStatus,
    run_exp074_panel,
    validate_exp074_report,
)

__all__ = [
    "EXPERIMENT_066_ID",
    "EXP066_CLAIM_NOTE",
    "FORBIDDEN_ATTENTION_CLAIMS",
    "AttentionFeasibilityResult",
    "MemoryAccounting",
    "QuantizedKV",
    "attention_full",
    "attention_materialized_compressed",
    "attention_streaming_compressed",
    "dequantize_kv_materialized",
    "estimate_attention_memory_bytes",
    "quantize_kv_int8_reference",
    "run_attention_feasibility_cell",
    "validate_exp066_report",
    "DEFAULT_MODEL_ID",
    "EXPERIMENT_067_ID",
    "EXPERIMENT_068_ID",
    "EXPERIMENT_069_ID",
    "EXPERIMENT_070_ID",
    "EXPERIMENT_071_ID",
    "EXPERIMENT_072_ID",
    "EXPERIMENT_073_ID",
    "EXPERIMENT_074_ID",
    "EXP067_CLAIM_NOTE",
    "EXP068_CLAIM_NOTE",
    "EXP069_CLAIM_NOTE",
    "EXP070_CLAIM_NOTE",
    "EXP071_CLAIM_NOTE",
    "EXP072_CLAIM_NOTE",
    "EXP073_CLAIM_NOTE",
    "EXP074_CLAIM_NOTE",
    "AttentionTolerancePolicy",
    "AttentionToleranceDecision",
    "OfflineAttentionStatus",
    "PHASE16D_REGRESSION_CELL",
    "compute_drift_metrics",
    "extract_qkv_from_qwen2_layer",
    "extract_qwen_model_architecture",
    "probe_qwen_architecture_support",
    "run_exp067_probe",
    "run_exp068_probe",
    "run_exp069_probe",
    "run_exp070_probe",
    "run_exp071_probe",
    "run_exp072_probe",
    "run_exp073_probe",
    "run_exp074_panel",
    "run_hf_attention_drift_cell",
    "validate_exp067_report",
    "validate_exp068_report",
    "validate_exp069_report",
    "validate_exp070_report",
    "validate_exp071_report",
    "validate_exp072_report",
    "validate_exp073_report",
    "validate_exp074_report",
]
